---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/9/28 6:15 PM
---

package.cpath = "./?.so"
local nsenter = require("nsenter")

print(os.execute("ifconfig"))
local ns = nsenter.new()
ns:enter(2436, "pid", "net", "mnt")
print(os.execute("ifconfig"))
print(os.execute("ps axu"))
ns:exit()
print(os.execute("ifconfig"))

ns:enter(2436, "pid", "net", "mnt")
print(os.execute("ifconfig"))
print(os.execute("ps axu"))
ns:exit()

ns:setns("/var/run/docker/netns/91dffb987944")
print(os.execute("ifconfig"))
ns:setns("/var/run/docker/netns/default")
print(os.execute("ifconfig"))