---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/9/28 6:15 PM
---

package.cpath = "./?.so"
local nsenter = require("nsenter")

print(os.execute("ifconfig"))
local ns = nsenter.new()
ns:enter(58834, "net")
print(os.execute("ifconfig"))
ns:exit()
print(os.execute("ifconfig"))
